version: '3.9'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: astro_app
    volumes:
      - ./app:/usr/src/app
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
